### ISSUE TITLE
タブの名前を変えたい

### ISSUE THREAD

**Issue by MiyamotoRin** [TakaminoRegent/AISpeculationQuiz#3]
タブの名前が「main streamlit」などと非常にわかりづらいので、「メインページ」などに変えたい

**Comment by MiyamotoRin** [comment]
[これ](https://data-analytics.fun/2022/07/10/streamlit-theme-page-settings/)が参考になりそう

**Comment by MiyamotoRin** [comment]
できた

**Comment by TKmatsu2008** [comment]
うるせーー
